{
  parserClass="com.kplugin.parser.KParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="K"
  psiImplClassSuffix="Impl"
  psiPackage="com.kplugin.psi"
  psiImplPackage="com.kplugin.psi.impl"

  elementTypeHolderClass="com.kplugin.psi.KTypes"
  elementTypeClass="com.kplugin.psi.KElementType"
  tokenTypeClass="com.kplugin.psi.KTokenType"
}



kFile ::= module_*

private module_ ::= MODULE WHITE_SPACE MODULE_NAME CRLF imports_block* ENDMODULE

imports_block ::= IMPORTS WHITE_SPACE MODULE_NAME CRLF

item_ ::= (property|COMMENT|CRLF)

property ::= (KEY? SEPARATOR VALUE?) | KEY

